deploy:
  on:
    branch: master
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  glob: !*.md
  bucket: "sc-lib-ds-static"
  upload_dir: sanskrit
  detect_encoding: true
  default_text_charset: 'utf-8'