language: ruby
cache: bundler
sudo: false
rvm:
 - 2.3
 - 2.4
 - 2.5
 - 2.6

deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  skip_cleanup: true
  glob: !*.md
  bucket: "sc-lib-ds-static"
  upload_dir: sanskrit
  detect_encoding: true
  default_text_charset: 'utf-8'